### ISSUE TITLE
Have an idea

### ISSUE THREAD

**Issue by smokenmirrors2** [llSourcell/bitcoin_prediction#13]
Can you see if you can validate my thoughts on being able to build a price prediction based on the number of short and long positions open on bitmex?
Check these charts out...
https://coinfarm.online/?tcs=1m

**Comment by smokenmirrors2** [comment]
I feel like im starting to see patterns after staring at it for so long

**Comment by fedecaccia** [comment]
@smokenmirrors2 great! please share with me some insights...

**Comment by smokenmirrors2** [comment]
@fedecaccia I have no idea how to write or build a prediction model using this data or how to collect it like they do... was hoping someone else would think its a good idea and try to do it
