### ISSUE TITLE
how was the sentiment index sampled in sentiment6.txt?

### ISSUE THREAD

**Issue by tonywangcn** [llSourcell/bitcoin_prediction#6]
Mean of all tweets? Why does the first few days have the same index?

**Comment by artem-hryb** [comment]
The Continuous_Stream_Sentiment.py has code that forms part of dataset:

from textblob import TextBlob

polarity = get_polarity(tweets,f1)
sentiment = np.mean(polarity)

this code base on input returns polarity of text from negative to positive.

**Comment by tonywangcn** [comment]
@artem-hryb Thanks !
